# Fastlane Docs: https://docs.fastlane.tools
# Actions Docs: https://docs.fastlane.tools/actions
# Plugins Docs: https://docs.fastlane.tools/plugins/available-plugins

XCODE_WORKSPACE_NAME = "Certified.xcworkspace"
XCODE_VERSION = "13.2.1"

default_platform(:ios)

platform :ios do
  desc "Test Certified App"
  lane :test do |options|
    xcversion(version: XCODE_VERSION)
    run_tests(scheme: "Certified Debug", project: XCODE_PROJECT_NAME)
  end

  desc "Release Certified App"
  lane :release do |options|
    keychain_name = "RunnerKeychain"
    create_keychain(
      name: keychain_name,
      password: ENV['KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
    )
    import_certificate(
      certificate_path: File.absolute_path("certs/distribution.p12"),
      certificate_password: ENV['CERTIFICATE_PASSWORD'],
      keychain_name: keychain_name,
      keychain_password: ENV['KEYCHAIN_PASSWORD']
    )
    install_provisioning_profile(
      path: File.absolute_path("profiles/distribution.mobileprovision")
    )
    xcversion(
      version: XCODE_VERSION
    )
    increment_build_number(
      build_number: ENV['GITHUB_RUN_NUMBER']
    )
    build_ios_app(
      workspace: XCODE_WORKSPACE_NAME,
      scheme: "Certified Release",
      clean: true,
      output_directory: File.absolute_path("ipa"),
      output_name: "certified.ipa"
    )
    upload_to_testflight(
      api_key_path: File.absolute_path("connect/QAX2TQQ74R.json"),
      ipa: File.absolute_path("ipa/certified.ipa"),
      skip_waiting_for_build_processing: true
    )
  end
end
